name: 每日签到

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 删除 uses: actions/checkout，改用 git 命令拉取（如果不需要代码仓库内容，甚至可以删掉这一步）
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master  # 明确指定拉取 master 分支
      
      - name: Run checkin
        run: |
          python -m pip install requests
          python3 glados.py
        env:
          GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
